config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: 'homes#top'
  get "terms", to: "homes#terms", as: "terms"
  get "policy", to: "homes#policy", as: "policy"
  get "about", to: "homes#about", as: "about"
  get "check", to: "users#check", as: "destroy_user_check"
  resources :posts do
    resources :favorites, only: [:create, :destroy]
    collection do
      get "get_category_children", defaults: { format: "json" }
    end
  end
  resources :users, only: [:index, :show] do
    resource :follow_relations, only: [:create, :destroy]
    get "followings", to: "follow_relations#followings"
    get "followers", to: "follow_relations#followers"
  end
end

app/views/layouts/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_favorite_btn.html.erb
<% if user_signed_in? %>
  <% if current_user.favorite?(post) %>
      <%= link_to post_favorite_path(post_id: post.id, id: current_user.favorites.find_by(post_id: post.id)), method: :delete do %>
        <span class="material-icons-outlined">favorite</span>
      <% end %>
  <% else %>
      <%= link_to post_favorites_path(post_id: post.id), method: :post do %>
        <span class="material-icons-outlined">favorite_border</span>
      <% end %>
  <% end %>
<% end %>

app/views/layouts/shared/_follow_btn.html.erb
<% if user_signed_in? && current_user != user %>
  <% if current_user.following?(user) %>
    <object>
      <%= link_to user_follow_relations_path(user.id), method: :delete  do %>
        <button class="button-dark follow-btn">フォロー中</button>
      <% end %>
    </object>
  <% else %>
    <object>
      <%= link_to user_follow_relations_path(user.id), method: :post do %>
        <button class="button-light follow-btn">フォローする</button>
      <% end %>
    </object>
  <% end %>
<% end %>

app/views/layouts/shared/_footer.html.erb
<!-- ======= Footer ======= -->
  <footer class="footer">
    <div class="footer-navi">
      <%= link_to "みんなのマイデザインとは？", about_path %><span></span>
      <%= link_to "利用規約", terms_path %><span></span>
      <%= link_to "プライバシーポリシー", policy_path %><span></span>
    </div>
    <div class="copyrights">
      <div class="container">
        <p>&copy; Nintendo 当サイト上で使用しているゲーム画像の著作権および商標権、その他知的財産権は、当該コンテンツの提供元に帰属します。</p>
        <p>&copy; Copyrights eStartup. All rights reserved. Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a></p>
        <p>&copy; 2024 Copyrights みんなのマイデザイン</p>
        <p class="credits">
          <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=eStartup
        -->
        </p>
      </div>
    </div>
  </footer><!-- End  Footer -->

app/views/layouts/shared/_header.html.erb
<!-- ======= Header ======= -->
<header id="header" class="header">
  <div class="header-container">
    <div class="logo", data-turbolinks='false'>
      <%= link_to root_path do %>
        <span>みんなの</span> </br>
        マイデザイン
      <% end %>
    </div>
    <div id="mobile-logo", data-turbolinks='false' >
      <%= link_to root_path do %>
        <span class=" md-48 material-icons">
          home
        </span>
      <% end %>
    </div>
    <div class="header-right">
      <%= search_form_for @q_header, class:"search-form-3" do |f| %>
        <%= f.search_field :title_or_user_name_or_text_or_tags_name_cont, placeholder: "キーワード検索" %>
        <button id="" type="submit"></button>
      <% end %>
      <nav class="pc-navbar">
        <ul class="navber-list">
          <% if user_signed_in? %>
            <li class="navber-item">
              <%= link_to new_post_path, class:"navber-link" do %>
                <span class="material-icons">add</span>投稿する
              <% end %>
            </li>
            <li class="navber-item">
              <%= link_to posts_path, class:"navber-link" do %>
                <span class="material-symbols-outlined">apparel</span>デザイン一覧
              <% end %>
            </li>
            <li class="navber-item" >
              <%= link_to users_path, class:"navber-link" do %>
                <span class="material-symbols-outlined">group</span>ユーザー
              <% end %>
            </li>
            <div class="dropdown">
              <button class="non-btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.user_image.attached? %>
                  <%= image_tag current_user.user_image.variant(resize_to_fill: [50, 50]), class:"user-icon user-header-image"%>
                <% else %>
                  <%= image_tag "user-default-icon.png", size: "50x50", class:"user-icon user-header-image" %>
                <% end %>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to user_path(current_user.id), class:"dropdown-item" do %>
                    マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_user_registration_path, class:"dropdown-item" do %>
                    アカウント編集
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class:"dropdown-item" do %>
                    ログアウト
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_check_path, class:"dropdown-item" do %>
                    退会手続き
                  <% end %>
                </li>
              </ul>
            </div>
          <% else %>
            <li class="navber-item">
              <%= link_to posts_path, class:"navber-link" do %>
                <span class="material-symbols-outlined">apparel</span>デザイン一覧
              <% end %>
            </li>
            <li class="navber-item">
              <%= link_to users_path, class:"navber-link" do %>
                <span class="material-symbols-outlined">group</span>ユーザー
              <% end %>
            </li>
            <li class="navber-item">
              <%= link_to new_user_session_path, class:"navber-link" do %>
                <span class="material-symbols-outlined">login</span>ログイン
              <% end %>
            </li>
            <li class="navber-item">
              <%= link_to new_user_registration_path, class:"navber-link" do %>
                <span class="material-symbols-outlined">person_add</span>新規登録
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>

      <div class="mobile-navbar">
        <div class="sp-menu">
          <input type="checkbox" id="sp-menu__check">
          <label for="sp-menu__check" class="sp-menu__box">
            <span></span>
          </label>
          <div class="sp-menu__content">
            <ul class="sp-menu__list">
              <% if user_signed_in? %>
                <li class="sp-menu__item">
                  <%= link_to new_post_path, class:"sp-menu__link" do %>
                    <span class="material-icons">add</span>投稿する
                  <% end %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to posts_path, class:"sp-menu__link" do %>
                    <span class="material-symbols-outlined">apparel</span>デザイン一覧
                  <% end %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to users_path, class:"sp-menu__link" do %>
                    <span class="material-symbols-outlined">group</span>ユーザー
                  <% end %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to user_path(current_user.id), class:"sp-menu__link" do %>
                    <span class="material-symbols-outlined">account_circle</span>マイページ
                  <% end %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to edit_user_registration_path, class:"sp-menu__link" do %>
                    <span class="material-symbols-outlined">edit</span>アカウント編集
                  <% end %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to destroy_user_session_path, method: :delete, class:"sp-menu__link" do %>
                    <span class="material-symbols-outlined">logout</span>ログアウト
                  <% end %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to "退会手続き", destroy_user_check_path, class:"sp-menu__link" %>
                  </li>
              <% else %>
                <li class="sp-menu__item">
                  <%= link_to "デザイン一覧", posts_path, class:"sp-menu__link" %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to "ユーザー", users_path, class:"sp-menu__link" %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to "ログイン", new_user_session_path, class:"sp-menu__link" %>
                </li>
                <li class="sp-menu__item">
                  <%= link_to "新規登録", new_user_registration_path, class:"sp-menu__link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/shared/_post_list.html.erb
<ul class="post-list">
  <% posts.each do |post| %>
    <li class="post-wrapper">
      <%= link_to post, class:"post" do %>
        <%= image_tag post.image.variant(resize_to_fill: [285, 170]), class:"post-image" %>
        <div class="post-title"><%= post.title %></div>
      <% end %>
      <div class="post-text">
        <%= link_to "by #{post.user.name}", post.user, class:"post-user-name" %>
        <div class="post-favorite">
          
          <div class="post-favorite-count"> 
              お気に入り<%= post.favorites_count %>件
          </div>
          <%= render 'layouts/shared/favorite_btn', post: post %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/shared/_tag_list.html.erb
<ul class="tag-list">
  <% tags.each do |tag| %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :tags_name_cont, value: tag.name %>
      <button class="non-btn badge rounded-pill">
        <%= image_tag "tag-icon.png", size: "14x14" %>
        <%= tag.name %>
      </button>
    <% end %>
  <% end %>
</ul>

app/views/layouts/shared/_tags.html.erb
<div class="tag-list">
  <% post.tags.each do |tag| %>
    <%= search_form_for @q do |f| %>
      <%= f.hidden_field :tags_name_cont, value: tag.name %>
      <button class="non-btn badge rounded-pill">
        <%= image_tag "tag-icon.png", size: "14x14" %>
        <%= tag.name %>
      </button>
    <% end %>
  <% end %>
</div>

app/views/layouts/shared/_user_list.html.erb
<ul class="user-list">
  <% users.each do |user| %>
    <li class="user-wrapper">
      <%= link_to user, class:"user-list-item" do %>
        <% if user.user_image.attached? %>
          <%= image_tag user.user_image.variant(resize_to_fill: [100, 100]), class:"user-icon user-list-image" %>
        <% else %>
          <%= image_tag "user-default-icon.png", size: "100x100", class:"user-icon user-list-image" %>
        <% end %>
        <div class="user-list-text">
          <div class="user-list-first-line">
            <div class="user-list-name">
              <%= user.name %>
            </div>
            <%= render "layouts/shared/follow_btn", user: user %>
          </div>
          <div class="user-list-second-line">
            <div class="user-count user-post-count">
              投稿 <span> <%= user.posts_count %></span> 件
            </div>
            <div class="user-count user-follow-count">
              <object>
                <%= link_to user_followings_path(user), class:"account-second-line-follow" do %>
                  フォロー <span><%= user.followings.count %></span>
                <% end %>
              </object>
            </div>
            <div class="user-count user-follower-count">
              <object>
                <%= link_to user_followers_path(user), class:"account-second-line-follow" do %>
                  フォロワー <span><%= user.followers.count %></span>
                <% end %>
              </object>
            </div>
          </div>
          <div class="user-list-third-line">
            <p class="user-list-profile">
              <%= strip_tags(user.profile.to_s).gsub(/[\n]/,"").strip.truncate(45)%>
            </p>
          </div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>