config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: 'homes#top'
  get "terms", to: "homes#terms", as: "terms"
  get "policy", to: "homes#policy", as: "policy"
  get "about", to: "homes#about", as: "about"
  get "check", to: "users#check", as: "destroy_user_check"
  resources :posts do
    resources :favorites, only: [:create, :destroy]
    collection do
      get "get_category_children", defaults: { format: "json" }
    end
  end
  resources :users, only: [:index, :show] do
    resource :follow_relations, only: [:create, :destroy]
    get "followings", to: "follow_relations#followings"
    get "followers", to: "follow_relations#followers"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # 1つの投稿に1枚画像を添付できるようにする
  has_one_attached :image
  # counter_chacheで投稿数を自動的にカウントし、読み取りを高速化
  belongs_to :user, counter_cache: true
  # 投稿が削除されたらお気に入りも削除
  has_many :favorites, dependent: :destroy
  # 中間テーブル「favorites」を経由して、userモデルと多対多の関係
  has_many :users, through: :favorites
  # 投稿が削除されたら投稿とタグの関連情報も削除
  has_many :post_tag_relations, dependent: :destroy
  # 中間テーブル「post_tag_relations」を経由して、tagモデルと多対多の関係
  has_many :tags, through: :post_tag_relations
  belongs_to :category


  # 投稿タイトルを必須化、かつ20文字以内に制限
  validates :title, presence: true, length: { maximum: 20 }
  # 投稿に紐づく作品IDを必須化
  validates :work_id, presence: true
  # 投稿に紐づく作者IDを必須化
  validates :author_id, presence: true
  # 本文は200文字以内に制限
  validates :text, length: { maximum: 200 }
  # 画像の添付は必須
  validates :image, presence: true
  # 画像サイズチェック
  validate :image_size

  # 画像サイズが5MBを超えていないかチェック
  def image_size
    if image.attached? && image.blob.byte_size > 5.megabytes
      errors.add(:image, 'は5MB以下である必要があります。')
    end
  end

  # ransack用のカスタム検索項目を定義し、お気に入り数で並び替えできるようにする
  ransacker :favorites_count do
    query = '(SELECT COUNT(favorites.post_id) FROM favorites where favorites.post_id = posts.id GROUP BY favorites.post_id)'
    Arel.sql(query)
  end

  # タグの作成、削除
  def save_tags(tags)
    # 入力されたタグを確認
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # 編集画面で削除された既存のタグをデータベースから削除する
    old_tags.each do |old_name|
      tag = Tag.find_by(name: old_name)
      self.tags.destroy(tag)
    end

    # 新たに入力されたタグをデータベースに追加（重複しているタグは追加しない）
    new_tags.uniq.each do |new_name|
      # タグを探してなければ、新しく作る
      tag = Tag.find_or_create_by(name: new_name)
      self.tags << tag
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # 投稿の作成・編集・更新・削除時にログインユーザーか確認
  before_action :authenticate_user!, only: ["new", "edit", "create", "update", "destroy"]
  # 投稿がユーザー自身のものであるか確認
  before_action :authenticate_post, only: ["edit", "update", "destroy"]
  # 親カテゴリー情報を取得（フォームや検索時に使用）
  before_action :set_parents, only: ["new", "edit", "index", "create", "update"]
  # 投稿編集・更新時に子カテゴリー情報を設定
  before_action :set_form_childs, only: ["edit", "update"]
  # 投稿検索画面で子カテゴリー情報を設定
  before_action :set_search_childs, only: ["index"]

   # 投稿一覧を表示（検索機能も含む）
  def index
    if params[:q].present?
      # 検索条件があれば、それに基づいて投稿を取得
      @q = Post.with_attached_image.preload(:user).ransack(params[:q])
      @posts = @q.result(distinct: true)
      # ヘッダー検索用の結果があれば、それを優先
      if @q_header
        @posts = @q_header.result(distinct: true)
      end
    else
      # 検索条件が無ければ、作成日時順に投稿を取得
      params[:q] = { sorts: 'created_at desc' }
      @q = Post.with_attached_image.preload(:user).ransack(params[:q])
      @posts = @q.result(distinct: true)
    end
  end

  # 投稿詳細を取得
  def show
    @q = Post.ransack(params[:q])
    @post = Post.find(params[:id])
  end

  # 新規投稿フォームを表示させるための処理
  def new
    @post = Post.new
  end

  # 投稿の編集フォームを表示させるための処理
  def edit
    @post = Post.find(params[:id])
    @tag_names = @post.tags.pluck(:name).join(',')
  end

  # 新しい投稿を作成
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    tag_names = params[:post][:tag_names].split(',')

    # 保存が成功した場合は、投稿にタグを関連付ける
    if @post.save
      @post.save_tags(tag_names)
      redirect_to :posts, notice: "投稿しました"
    # 失敗した場合は、新規作成画面を再表示
    else
      render "new"
    end
  end

   # 投稿を更新
  def update
    @post = Post.find(params[:id])
    # 入力されたタグを配列に入れる
    tag_names = params[:post][:tag_names].split(',')
    # 更新が成功した場合は、投稿にタグを紐づける
    if @post.update(post_params)
      @post.save_tags(tag_names)
      redirect_to :post, notice: "更新しました"
    # 失敗した場合は、編集画面を再表示
    else
      render "edit"
    end
  end

  # 投稿を削除
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :posts, notice: "投稿を削除しました"
  end

  # 新規投稿フォームで、親カテゴリーに紐づく子カテゴリーを取得
  # JSON用のアクション
  def get_category_children
    # ajax通信で送られてきた親カテゴリーから、紐づく小カテゴリーを取得
    @category_children = Category.find(params[:parent_id].to_s).children
  end

  private

  # フォームや検索時に、親カテゴリーのみを取得
  def set_parents
    @set_parents = Category.where(ancestry: nil)
  end

  # 編集フォームで、親カテゴリーに紐づく子カテゴリーを取得
  def set_form_childs
    post = Post.find(params[:id])
    if !post.category.root?
      @set_childs = Category.where(ancestry: post.category.parent.id)
    end
  end

  # 検索時に、選択されたカテゴリーの子カテゴリーを取得
  def set_search_childs
    # 検索パラメータが存在しており、かつカテゴリーが選択されている場合
    if (params[:q].present?) && (params[:q][:category_ancestry_or_category_id_eq].present?)
      # 親カテゴリーを取得
      @exist_category = Category.find(params[:q][:category_ancestry_or_category_id_eq])
      # 親カテゴリーに紐づく子カテゴリーを取得
      @set_childs = Category.where(ancestry: @exist_category.id)
    end
  end

  # 投稿フォームのパラメータを許可
  def post_params
    params.require(:post).permit(:title, :image, :text, :work_id, :author_id, :user_id, :category_id)
  end

  # ユーザーが投稿の所有者であることを確認
  def authenticate_post
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
      redirect_to :post, alert: "他のユーザーの投稿は編集・削除できません。"
    end
  end
end

app/views/posts/_favorites.html.erb
<p class="contents-container-title"> お気に入りの投稿 : <%= @favorite_posts.count %> 件</p>
<ul class="post-list">
    <% @favorite_posts.each do |post| %>
      <li class="post-wrapper">
          <%= link_to post, class:"post" do %>
              <%= image_tag post.image.variant(resize_to_fill: [285, 170]), class:"post-image" %>
              <div class="post-title"><%= post.title %></div>
              <p class="post-id"><%= post.work_id %></p>
          <% end %>
          <div class="post-under">
            <%= link_to "by #{post.user.name}", post.user, class:"post-user-name" %>
            <div class="favorite">
              <div class="favorite-count"> お気に入り<%= post.favorites.count %>件 </div>
              <%= render 'posts/favorite_button', {post: post} %>
            </div>
          </div>
        </li>
    <% end %>
</ul>        

app/views/posts/_post_list.html.erb
<ul class="post-list">
  <% posts.each do |post| %>
    <li class="post-wrapper">
      <%= link_to post, class:"post" do %>
        <%= image_tag post.image.variant(resize_to_fill: [285, 170]), class:"post-image" %>
        <div class="post-title"><%= post.title %></div>
      <% end %>
      <div class="post-text">
        <%= link_to "by #{post.user.name}", post.user, class:"post-user-name" %>
        <div class="post-favorite">
          <div class="post-favorite-count"> お気に入り<%= post.favorites_count %>件 </div>
          <%= render 'favorites/btn', post: post %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<main class="contents-container">
  <div class="bredcrumb">
    <%= link_to "ホーム", root_path %>
    <span></span><%= link_to "マイデザイン", posts_path %>
    <span></span><%= link_to @post.title, post_path(@post.id) %>
    <span></span>投稿を編集
  </div>
  <div class="form-wrapper">
    <h3 class="form-title">マイデザインを編集</h3>
      <%= form_with model: @post, class:"form" do |f| %>
        <%= render 'layouts/shared/error_messages', model: f.object %>
        <div class="row mb-3">
          <%= f.label :title ,"タイトル", class: "col-sm-4 col-form-label required" %>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", maxlength: 20, required: true %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :image ,"画像", class: "col-sm-4 col-form-label required" %>
          <div class="col-sm-8">
            <%= f.file_field :image, class: "form-control", onchange: "previewImage(this)", accept: 'image/jpg,image/jpeg,image/png,image/gif' %>
            <%= image_tag @post.image, id:"preview" %>
            <script>
            function previewImage(obj){
              var fileReader = new FileReader();
              fileReader.onload = function() {
                var element = document.getElementById('preview');
                element.src = fileReader.result;
              }
              fileReader.readAsDataURL(obj.files[0]);
            };
            </script>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :work_id ,"作品ID", class: "col-sm-4 col-form-label required" %>
          <div class="col-sm-8">
            <%= f.text_field :work_id, class: "form-control", required: true, maxlength: 17, pattern: "MO-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}", title: "半角英数字（英大文字）で MO-XXXX-XXXX-XXXXの形式で入力して下さい。", placeholder: "MO-XXXX-XXXX-XXXX" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :author_id ,"作者ID", class: "col-sm-4 col-form-label required" %>
          <div class="col-sm-8">
            <%= f.text_field :author_id, class: "form-control", required: true, maxlength: 17, pattern: "MA-[0-9]{4}-[0-9]{4}-[0-9]{4}", title: "半角英数字（英大文字）で MA-XXXX-XXXX-XXXXの形式で入力して下さい。", placeholder: "MA-XXXX-XXXX-XXXX" %>
          </div>
        </div>
        <% if @post.category.root? %>
          <div class="append__category">
            <div class="row mb-3">
              <%= f.label :category_id ,"カテゴリー", class: "col-sm-4 col-form-label required", local: true %>
              <div class="col-sm-8">
                <%= f.collection_select :category_id, @set_parents, :id, :name,{ include_blank: "選択してください"}, class:"select_field form-control", id:"post_category_id", required: true %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="append__category">
            <div class="row mb-3">
              <%= f.label :category_id ,"カテゴリー", class: "col-sm-4 col-form-label required", local: true %>
              <div class="col-sm-8">
                <%= f.collection_select :category_id, @set_parents, :id, :name,{ include_blank: "選択してください", selected: @post.category.parent.id}, class:"select_field form-control", id:"post_category_id", required: true %>
              </div>
            </div>
            <div class="row mb-3" id="exist_children_wrapper">
              <%= f.label :category_id ,"サブカテゴリー", class: "col-sm-4 col-form-label required", local: true %>
              <div class="col-sm-8">
                <%= f.collection_select :category_id, @set_childs, :id, :name,{ include_blank: "選択してください", selected: @post.category.id}, class:"select_field form-control", id:"post_category_id", required: true %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="row mb-3">
          <%= f.label :tag_names ,"タグ", class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= f.text_area :tag_names, value: @post.tags.map(&:name).join(","), class: 'tag-input form-control', placeholder: "複数追加する場合は、カンマ(,)で区切って入力してください。" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :text ,"コメント", class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= f.text_area :text, class: "form-control", maxlength: 200 %>
          </div>
        </div>
        <div class="form-btn-wrapper">
          <%= f.submit "更新する", class:"button-dark submit-btn button" %>
        </div>
      <% end %>
  </div>
</main>

<% if @post.errors.any? %>
  <%= javascript_pack_tag 'posts/edit_render.js' %>
<%end%>

app/views/posts/index.html.erb
<main class="contents-container">
  <div class="bredcrumb"> 
      <%= link_to "ホーム", root_path %>
      <span></span>デザイン一覧
      <% if params[:q][:tags_name_cont].present? %>
      <span></span>タグ：<%=params[:q][:tags_name_cont]%>
      <% end %>
      <% if @exist_category.present?%>
        <%= search_form_for @q do |f| %>
          <%= f.hidden_field :category_ancestry_or_category_id_eq, value: @exist_category.id %>
          <span></span><%= f.submit @exist_category.name, class:"non-btn hidden-button" %>
        <% end %>
      <% end %>
      <% if @exist_child_category.present? %>
        <%= search_form_for @q do |f| %>
          <%= f.hidden_field :category_ancestry_or_category_id_eq, value: @exist_child_category.id %>
          <%= f.hidden_field :category_id_eq, value: @exist_child_category.id %>
          <span></span><%= f.submit @exist_child_category.name, class:"non-btn hidden-button" %>
        <% end %>
      <% end %>
  </div>
  
  <div class="contents-wrapper">
    <%= search_form_for @q, class:"search-form" do |f| %>
      <%= f.select( :sorts, { '新着順': 'created_at desc', '人気順': 'favorites_count desc' }, { selected: params[:q][:sorts]}) %>
        <div class="append__category search-select-form">
            <%= f.collection_select :category_ancestry_or_category_id_eq, @set_parents, :id, :name, { include_blank: "カテゴリー"}, class:"search-select", id:"search_category_id" %>
            <% if @exist_category.present? &&  @exist_category.children.present? %>
              <%= f.collection_select :category_id_eq, @set_childs, :id, :name, { include_blank: "サブカテゴリー" }, class:"search-select-child", id:"search_category_id" %>
            <% end %>
        </div>
      <%= f.search_field :title_or_user_name_or_text_or_tags_name_cont, placeholder: "キーワード検索", class:"search-post-keyword-form" %>
      <button id="search_btn" type="submit">検索</button>
    <% end %>
    <div class="contents-title">
      <div class="contents-count">
        <%= @posts.count %> 件の結果
      </div>
    </div>
    <%= render 'layouts/shared/post_list', posts: @posts %>
  </div>
</main>

app/views/posts/new.html.erb
<main class="contents-container">
  <div class="bredcrumb">
    <%= link_to "ホーム", root_path %>
    <span></span><%= link_to "デザイン一覧", posts_path %>
    <span></span>新規投稿
  </div>
  <div class="form-wrapper">
    <h3 class="form-title">マイデザインを投稿</h3>
      <%= form_with model: @post, class:"form" do |f| %>
        <%= render 'layouts/shared/error_messages', model: f.object %>
        <div class="row mb-3">
          <%= f.label :title ,"タイトル", class: "col-sm-4 col-form-label required" %>
          <div class="col-sm-8">
            <%= f.text_field :title, class: "form-control", maxlength: 20, required: true %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :image ,"画像", class: "col-sm-4 col-form-label required", local: true %>
          <div class="col-sm-8">
            <%= f.file_field :image, class: "form-control", onchange: "previewImage(this)", accept: 'image/jpg,image/jpeg,image/png,image/gif', required: true %>
            <img id="preview">
            <script>
            function previewImage(obj){
              var fileReader = new FileReader();
              fileReader.onload = function() {
                var element = document.getElementById('preview');
                element.src = fileReader.result;
              }
              fileReader.readAsDataURL(obj.files[0]);
            }
            </script>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :work_id ,"作品ID", class: "col-sm-4 col-form-label required" %>
          <div class="col-sm-8">
            <%= f.text_field :work_id, class: "form-control", required: true, maxlength: 17, pattern: "MO-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}", title: "半角英数字（英大文字）で MO-XXXX-XXXX-XXXXの形式で入力して下さい。", placeholder: "MO-XXXX-XXXX-XXXX" %>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :author_id ,"作者ID", class: "col-sm-4 col-form-label required" %>
          <div class="col-sm-8">
            <%= f.text_field :author_id, class: "form-control", required: true, maxlength: 17, pattern: "MA-[0-9]{4}-[0-9]{4}-[0-9]{4}", title: "半角英数字（英大文字）で MA-XXXX-XXXX-XXXXの形式で入力して下さい。", placeholder: "MA-XXXX-XXXX-XXXX" %>
          </div>
        </div>
        <div class="append__category">
          <div class="row mb-3">
            <%= f.label :category_id ,"カテゴリー", class: "col-sm-4 col-form-label required", local: true %>
            <div class="col-sm-8">
              <%= f.collection_select :category_id, @set_parents, :id, :name, { include_blank: "選択してください"}, maxlength: 17, class:"select_field form-control", id:"post_category_id", required: true %>
            </div>
          </div>
        </div>
        <div class="row mb-3">
          <%= f.label :tag_names ,"タグ", class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= f.text_area :tag_names, class: 'tag-input form-control', placeholder: "複数追加する場合は、カンマ(,)で区切って入力してください。" %>
          </div>
        </div>
         <div class="row mb-3">
          <%= f.label :text ,"コメント", class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= f.text_area :text, class: "form-control", maxlength: 200 %>
          </div>
        </div>
        <div class="form-btn-wrapper">
          <%= f.submit "投稿する", class:"button-dark submit-btn button" %>
        </div>
      <% end %>
  </div>
</main>

<% if @post.errors.any? %>
  <%= javascript_pack_tag 'posts/new_render.js' %>
<%end%>

app/views/posts/show.html.erb
<main class="contents-container">
  <div class="bredcrumb">
    <%= link_to "ホーム", root_path %>
    <span></span><%= link_to "デザイン一覧", posts_path %>
    <% # 親カテゴリがある場合の処理 %>
    <% if @post.category.parent.present? %>
      <% # 親カテゴリと子カテゴリをパンくずリストとして表示 %>
      <% # 親カテゴリをクリックすると当該カテゴリの検索結果画面に遷移させる %>
      <%= search_form_for @q do |f| %>
        <%= f.hidden_field :category_ancestry_or_category_id_eq, value: @post.category.parent.id %>
        <span></span><%= f.submit @post.category.parent.name, class:"non-btn hidden-button" %>
      <% end %>
      <% # 子カテゴリをクリックすると当該カテゴリの検索結果画面に遷移させる %>
      <%= search_form_for @q do |f| %>
        <%= f.hidden_field :category_ancestry_or_category_id_eq, value: @post.category.parent.id %>
        <%= f.hidden_field :category_id_eq, value: @post.category.id %>
        <span></span><%= f.submit @post.category.name, class:"non-btn hidden-button" %>
      <% end %>
    <% # 親カテゴリがない場合の処理 %>
    <% else %>
      <% # 一つのカテゴリをパンくずリストとして表示 %>
      <% # カテゴリをクリックすると当該カテゴリの検索結果画面に遷移させる %>
      <%= search_form_for @q do |f| %>
        <%= f.hidden_field :category_ancestry_or_category_id_eq, value: @post.category.id %>
        <span></span><%= f.submit @post.category.name, class:"non-btn hidden-button" %>
      <% end %>
    <% end %>
    <span></span><%= @post.title %>
  </div>
  <div class="post-show-wrapper">
    <div class="post-show-title-wrapper">
      <h3 class="post-show-title"><%= @post.title %></h3>
      <div class="post-show-user">
      <% # ユーザー画像がある場合はそれを表示、なければデフォルト画像 %>
      <% if @post.user.user_image.attached? %>
        <%= image_tag @post.user.user_image.variant(resize_to_fill: [50, 50]), class:"user-icon post-show-user-image"%>
      <% else %>
        <%= image_tag "user-default-icon.png", size: "50x50", class:"user-icon post-show-user-image" %>
      <% end %>
      <div class="post-show-user-name"><%=link_to @post.user.name, user_path(@post.user.id) %></div>
      </div>
    </div>
    <div class="post-show-contents">
      <%= image_tag @post.image.variant(resize_to_fill: [600, 350]), class:"post-show-image"%>
      <div class="post-show-contents-right">
        <div class="post-show-text">
          <div class="post-show-first-line">
            <div class="post-show-first-line-left">
              <p class="post-show-favorite-count"> お気に入り<%= @post.favorites.count %>件 </p>
              <%= render 'layouts/shared/favorite_btn', post: @post %>
            </div>
            <p class="post-show-first-line-right"><%=l @post.created_at %></p>
          </div>
          <% # タグがある場合はタグ表示部分を読み込み %>
          <% if @post.tags.present? %>
            <div class="mb-3">
              <%= render 'layouts/shared/tags', post: @post %>
            </div>
          <% end %>
          <p class="post-show-id">作品ID : <%= @post.work_id %></p>
          <p class="post-show-id">作者ID : <%= @post.author_id %></p>
          <p class="post-show-comment"><%= @post.text %></p>
        </div>
      </div>
    </div>
    <% # 投稿者本人であれば編集・削除ボタンを表示 %>
    <% if @post.user == current_user %>
      <div class="post-show-btns">
        <div class="post-show-btns-right">
          <%= link_to [:edit, @post] do %>
            <button class="button-light edit-btn">編集</button>
          <% end %>
          <%= link_to @post, method: :delete, data: { confirm: "本当に削除しますか？" } do %>
            <button class="button-dark delete-btn">削除</button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</main>